# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    mappings:
        meuble_image:
            uri_prefix: /uploads/image/meuble
            upload_destination: '%kernel.project_dir%/public/uploads/image/meuble'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true